config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  get 'reviews/index'
  resources :products

  # get 'products', to: 'products#index', as: 'products'
  # get 'products/:id', to: 'products#show', as: 'product', id: /\d+/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  enum :status, %w[fresh old not_available]
  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :name, uniqueness: true
  after_save_commit :log_product_saved
  after_destroy_commit :log_product_destroyed

  validate :validate_name

  # def name
  #   "This is #{super}"
  # end

  def validate_name
    if name.present? && name.include?('X')
      errors.add(:name, 'X is found in Name')
    end
  end

  private

  def log_product_saved
    puts "=============\nProduct saved in the database\n============="
  end

  def log_product_destroyed
    puts "=============\nProduct deleted from the database\n============="
  end
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.order(created_at: :desc).page(params[:page]).per(3)
  end

  def show
    @product = Product.find(params[:id])
  end

  # Creates an object of product without saving it
  def new
    @product = Product.new
  end

  # Creates a product with handling the success and error condition
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "#{@product.name} was successfully added." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity, alert: 'Invalid Input' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action for deleting product
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to root_path, status: :see_other, alert: 'Item was successfully deleted.'
    else
      redirect_to @products, alert: 'Something went wrong'
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "#{@product.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Filters params using Strong Parameters
  def product_params
    params.require(:product).permit(:name, :description, :image_url, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.order(created_at: :desc).page(params[:page]).per(3)
  end

  # def create
  #   @review = Review.new(params.require(:review).permit(:content))
  #   @review.save!
  #   redirect_to reviews_index_path
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def show_errors(object, field)
    object.errors[field] unless object.errors.blank?
  end
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <title>Store</title>
    <%= javascript_importmap_tags %>
  </head>

  <body class="store-container text-center d-flex w-100 h-100 p-3 mx-auto flex-column ">
    <%= render partial: '/shared/product/store_alerts' %>
    <%= render partial: '/shared/navbar' %>
    <%= yield %>
    <%= render partial: '/shared/footer' %>
  </body>
</html>

app/views/products/edit.html.erb
<h2>Edit Product Here</h2>
<br/>
<%= render partial: '/shared/product/form' %>
<%= link_to 'Back', product_path(@product) %>

app/views/products/index.html.erb
<div class="pt-5">
<% if @products.count > 0 %>
  <%= render partial: '/shared/product/products-list' %>
<br>
<%= paginate @products, :window => 1%>
<% else %>
   <%= render partial: '/shared/product/empty-store' %>
<%end%>
</div>

app/views/products/new.html.erb
<h2>Add New Product Here</h2>
<br/>
<%= render partial: '/shared/product/form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% cache(@product) do%>
<div class="pt-5">
<h2><strong><%= @product.name%></strong></h2>
<p><%= @product.description%></p>
<p>
  <strong>Price: </strong>
  <%= number_to_currency(number_to_human(@product.price), unit:'RS ') %>
</p>
<p>
<%= link_to "Delete", product_path(@product), class: "delete-button", data: { turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>
  <%= link_to 'Edit', edit_product_path(@product) %>
  <%= link_to 'Back', products_path %>
</p>
</div>
<%end%>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<br>
<%= render partial: '/shared/review/reviews_list' %>
<br>
<%= paginate @reviews, :window => 1%>

app/views/shared/_footer.html.erb
<% cache do%>
  <footer class="footer mt-auto pb-3 pt-3">
          <div class="inner">
            <p>Copyright &copy; <a href="https://github.com/asadtariq-dev/">Asad Tariq</a></p>
          </div>
  </footer>
<%end%>

app/views/shared/_item.html.erb
<% @products.each do |product| %>
<div class="product-item border rounded p-3">
<%# link_to "Delete", root_path, method: :destroy, data: { turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>
<h2><strong><%= product.name%></strong> </h2>
<p><%= number_to_currency(product.price, :unit => "Rs ", :delimeter=>",", :precision => 0) %></p>
<p>Added: <%= time_ago_in_words(product.created_at) %> ago</p>

<p><%= link_to 'Details', product %></p>
</div>
<br/>
<% end %>

app/views/shared/_navbar.html.erb
<% cache do%>
  <header class="head mb-auto container pt-4">
          <div class="inner">
            <h3 class="head-name"><a href="/">Store</a></h3>
            <nav class="nav nav-head justify-content-center">
              <a class="nav-link active" href="/products">Home</a>
              <a class="nav-link" href="/products/new">Add Product</a>
              <a class="nav-link" href="/reviews/index">Reviews</a>
            </nav>
          </div>
          <br/><br/>
  </header>
<% end %>

app/views/shared/product/_empty-store.html.erb
<h3> Store is empty</h3>
<h4><%= link_to 'Add Product', '/products/new' %></h4>

app/views/shared/product/_form.html.erb
<% cache do%>
  <div class="form-container d-flex justify-content-center w-60 mx-auto flex-column ">
    <%= form_with(model: @product) do |form| %>

      <div class="row mb-2">
        <%= form.text_field :name, placeholder: "Name", size:'45rem', class: "inner-body mw-4" %><br>
      </div>

        <p class="error">
      <% if @product.errors.any? %>
          <% show_errors(@product, 'name').each do |error| %>
            Name <%= error %><br>
          <% end %>
      <%end%>
        </p>


      <div class="row mb-2">
        <%= form.text_field :description, placeholder: "Description", size:'45rem', class: "inner-body" %><br>
      </div>

        <p class="error">
      <% if @product.errors.any? %>
          <% show_errors(@product, 'description').each do |error| %>
            Description <%= error %><br>
          <% end %>
      <%end%>
        </p>


      <div class="row mb-2">
        <%= form.text_field :price, placeholder: "Price", size:'45rem', class: "inner-body"%><br>
      </div>

        <p class="error">
      <% if @product.errors.any? %>
          <% show_errors(@product, 'price').each do |error| %>
            Price <%= error %><br>
          <% end %>
      <%end%>
        </p>


      <div class="row mb-2">
        <%= form.text_field :image_url, placeholder: "Image", size:'45rem', class: "inner-body"%><br>
      </div>

        <p class="error">
      <% if @product.errors.any? %>
          <% show_errors(@product, 'image_url').each do |error| %>
            Image <%= error %><br>
          <% end %>
      <%end%>
        </p>


      <br/>
      <div class="row mb-2">
        <%= form.submit 'Create Product', class:"form-btn", data: {:disable_with => 'Creating'}%>
      </div>
    <% end %>
  </div>
<%end%>

app/views/shared/product/_products-list.html.erb
<% @products.each do |product| %>
  <div class="product-item border rounded p-3">
    <h2><strong><%= product.name%></strong> </h2>
    <p><%= number_to_currency(product.price, :unit => "Rs ", :delimeter=>",", :precision => 0) %></p>
    <p>Added: <%= time_ago_in_words(product.created_at) %> ago</p>
    <p><%= link_to 'Details', product %></p>
  </div>
  <br/>
<% end %>

app/views/shared/product/_store_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/review/_reviews_list.html.erb
<% @reviews.each do |review| %>
  <div class="product-item border rounded p-3">
    <h3><strong><%= review.customer_name%></strong></h3>
    <h4><%= review.content%></h4>
    <p><%= time_ago_in_words(review.created_at) %> ago</p>
  </div>
  <br/>
<% end %>